platform :ios, '13.3'
target 'Menlo Hacks' do
    use_frameworks!
    pod 'Bolts'
    pod 'AFNetworking'
    pod 'JNKeychain'
    pod 'Realm'
    pod 'PusherSwift'
    pod 'PushNotifications'
    pod 'Parchment'
    pod 'SCLAlertView-Objective-C'
    pod 'TTTAttributedLabel'
    pod 'AFMInfoBanner'

end

